/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Woman(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/models/character/woman.gltf"
  );
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorig2Hips} />
          <skinnedMesh
            name="Ch22_Body"
            geometry={nodes.Ch22_Body.geometry}
            material={materials["Ch22_body.003"]}
            skeleton={nodes.Ch22_Body.skeleton}
          />
          <skinnedMesh
            name="Ch22_Eyelashes"
            geometry={nodes.Ch22_Eyelashes.geometry}
            material={materials["Ch22_hair.003"]}
            skeleton={nodes.Ch22_Eyelashes.skeleton}
          />
          <skinnedMesh
            name="Ch22_Hair"
            geometry={nodes.Ch22_Hair.geometry}
            material={materials["Ch22_hair.003"]}
            skeleton={nodes.Ch22_Hair.skeleton}
          />
          <skinnedMesh
            name="Ch22_Pants"
            geometry={nodes.Ch22_Pants.geometry}
            material={materials["Ch22_body.003"]}
            skeleton={nodes.Ch22_Pants.skeleton}
          />
          <skinnedMesh
            name="Ch22_Shirt"
            geometry={nodes.Ch22_Shirt.geometry}
            material={materials["Ch22_body.003"]}
            skeleton={nodes.Ch22_Shirt.skeleton}
          />
          <skinnedMesh
            name="Ch22_Sneakers"
            geometry={nodes.Ch22_Sneakers.geometry}
            material={materials["Ch22_body.003"]}
            skeleton={nodes.Ch22_Sneakers.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/character/woman.gltf");
